/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author gilan
 */
public class InputPemesanan extends javax.swing.JFrame {

    /**
     * Creates new form InputPemesanan
     */
    public InputPemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label4 = new java.awt.Label();
        jRadioButton1 = new javax.swing.JRadioButton();
        label5 = new java.awt.Label();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label1.setText("PEMESANAN JASA");
        getContentPane().add(label1);
        label1.setBounds(29, 21, 320, 52);

        label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label2.setText("Nama");
        getContentPane().add(label2);
        label2.setBounds(29, 105, 60, 24);
        getContentPane().add(textField1);
        textField1.setBounds(99, 105, 224, 27);
        getContentPane().add(textField2);
        textField2.setBounds(99, 142, 224, 27);

        label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label3.setText("No Telp");
        getContentPane().add(label3);
        label3.setBounds(29, 142, 60, 24);
        getContentPane().add(textField3);
        textField3.setBounds(99, 179, 224, 56);

        label4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label4.setText("Alamat");
        getContentPane().add(label4);
        label4.setBounds(29, 179, 60, 24);

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton1.setText("Paket1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(39, 302, 81, 25);

        label5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label5.setText("Daftar Pilihan Paket");
        getContentPane().add(label5);
        label5.setBounds(29, 263, 294, 29);

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton2.setText("Paket1");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(39, 330, 81, 25);

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton3.setText("Paket1");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(120, 330, 83, 25);

        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton4.setText("Paket1");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(120, 302, 83, 25);

        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton5.setText("Paket1");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(203, 330, 83, 25);

        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton6.setText("Paket1");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(203, 302, 83, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
